#!/bin/sh
#
# Copyright (C) Mellanox Technologies Ltd. 2001-2019.  ALL RIGHTS RESERVED.
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance, use non-portable CPU optimizations.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/configure-release \
	--enable-optimizations \
	"$@"
echo "Opt build, Start: dump config.h"
if [ -f ${basedir}/../config.h]; then
    cat ${basedir}/../config.h
else
    ls -l ${basedir}
    ls -l ${basedir}/../
fi
echo "Opt build, End: dump config.h"
