#!/bin/sh
#
# Copyright (C) Mellanox Technologies Ltd. 2001-2014.  ALL RIGHTS RESERVED.
#
# See file LICENSE for terms.
#

#
# UCX build for profiling purposes.
# Some extra code to ease performance debugging.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/../configure \
	--disable-logging \
	--disable-debug \
	--disable-assertions \
	--disable-params-check \
	--enable-backtrace-detail \
	--enable-profiling \
	--enable-frame-pointer \
	--enable-stats \
	"$@"
echo "Prof build, Start: dump config.h"
if [ -f ${basedir}/../config.h]; then
    cat ${basedir}/../config.h
else
    ls -l ${basedir}
    ls -l ${basedir}/../
fi
echo "Prof build, End: dump config.h"
