#!/bin/sh
#
# Copyright (C) Mellanox Technologies Ltd. 2001-2014.  ALL RIGHTS RESERVED.
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance while maintaining portability.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/../configure \
	--disable-logging \
	--disable-debug \
	--disable-assertions \
	--disable-params-check \
	"$@"
echo "Rel build, Start: dump config.h"
if [ -f ${basedir}/../config.h]; then
    cat ${basedir}/../config.h
else
    ls -l ${basedir}
    ls -l ${basedir}/../
fi
echo "Rel build, End: dump config.h"
