#!/bin/sh
#
# Copyright (C) Mellanox Technologies Ltd. 2001-2016.  ALL RIGHTS RESERVED.
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance plus multithreading support.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/../contrib/configure-release \
	--enable-mt \
	"$@"
echo "Rel mt build, Start: dump config.h"
if [ -f ${basedir}/../config.h]; then
    cat ${basedir}/../config.h
else
    ls -l ${basedir}
    ls -l ${basedir}/../
fi
echo "Rel mt build, End: dump config.h"
